lr_finder:
  enable: False
  mode: TPE
  stop_after: False
  num_epochs: 6
  step: 0.001
  epochs_warmup: 1
  path_to_savefig: 'lr_finder.jpg'
  max_lr: 0.029
  min_lr: 0.005
  n_trials: 15

model:
  name: 'efficientnet_b0'
  type: 'multilabel'
  pretrained: True
  save_all_chkpts: False
  feature_dim: 1280
  dropout_cls:
    p: 0.1

custom_datasets:
  roots: ['datasets/coco/train.json', 'datasets/coco/val.json']
  types: ['multilabel_classification', 'multilabel_classification']
  names: ['COCO_train', 'COCO_val']

data:
  root: './'
  sources: ['COCO_train']
  targets: ['COCO_val']
  height: 448
  width: 448
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  save_dir: 'experiments/efficientnet/coco'
  workers: 12
  transforms:
    random_flip:
      enable: True
      p: 0.5
    randaugment:
      enable: True
    cutout:
      enable: True
      p: 0.35
      cutout_factor: 0.3

loss:
  name: 'asl'
  softmax:
    s: 1.0
    compute_s: False
  asl:
    gamma_pos: 0.
    gamma_neg: 4.

sampler:
  train_sampler: 'RandomSampler'

train:
  optim: 'sam'
  lr: 0.0002
  nbd: True
  max_epoch: 80
  weight_decay: 5e-4
  batch_size: 45
  lr_scheduler: 'onecycle'
  pct_start: 0.2
  early_stoping: True
  train_patience: 5
  lr_decay_factor: 1000
  deterministic: True
  train_patience: 5
  gamma: 0.1
  ema:
    enable: True
    ema_decay: 0.9995
  sam:
    rho: 0.05

test:
  batch_size: 64
  evaluate: False
  eval_freq: 1
