algo_backend:
  description: Internal Algo Backend parameters
  header: Internal Algo Backend parameters
  model: main_model.yaml
  model_name: image classification model
  template: template.yaml
  type: PARAMETER_GROUP
  visible_in_ui: false
description: Configuration for an object detection task
header: Configuration for an object detection task
learning_parameters:
  batch_size:
    affects_outcome_of: TRAINING
    default_value: 32
    description: The number of training samples seen in each iteration of training.
      Increasing this value improves training time and may make the training more
      stable. A larger batch size has higher memory requirements.
    editable: true
    header: Batch size
    max_value: 512
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: Increasing this value may cause the system to use more memory than available,
      potentially causing out of memory errors, please update with caution.
  description: Learning Parameters
  header: Learning Parameters
  max_num_epochs:
    affects_outcome_of: TRAINING
    default_value: 200
    description: Increasing this value causes the results to be more robust but training
      time will be longer.
    editable: true
    header: Maximum number of training epochs
    max_value: 100000
    min_value: 1
    type: INTEGER
    ui_rules:
      action: DISABLE_EDITING
      operator: AND
      rules: []
      type: UI_RULES
    visible_in_ui: true
    warning: null
  type: PARAMETER_GROUP
  visible_in_ui: true
type: MODEL_CONFIG
visible_in_ui: true
